name: Simple CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run simple check
        run: echo "CI pipeline is running"
      -uses: actions/setup-python@v5

      with:
        python-version: "3.12"
        
      -run: pip install -r requirement.txt
      -run: pytest
      
